const churchs = [
    { label: "Sabanita" },
    { label: "Yopal" },
    { label: "Nueva Guayana" },
    { label: "Brisas del Orinoco" },
    { label: "Próceres" },
    { label: "Nazareth" },
    { label: "Llano Alto" },
    { label: "Prado del Este" },
    { label: "Gran Sábana" },
    { label: "Central Bolívar" },
    { label: "Nueva República" },
    { label: "Cambao" },
    { label: "Moreas" },
    { label: "Betel" },
    { label: "Shell" },
    { label: "Maipure" },
    { label: "Manahaim" },
    { label: "Villa Lola" },
    { label: "Soledad" },
    { label: "Principal" },
    { label: "Metropolitana" },
    { label: "Angosturita 1" },
    { label: "Angosturita 2" },
    { label: "Angostura" },
    { label: "Grimaldi" },
    { label: "Itoyponkon" },
    { label: "Cardoso" },
    { label: "Giraluna" },
    { label: "Bicentenario" },
    { label: "Hipódromo" },
    { label: "Democracia" },
    { label: "El Este" },
    { label: "19 de Abril" },
    { label: "San Ignacio" },
    { label: "Cuyuni" },
    { label: "Grupo Peniel" },
    { label: "El Sur" },
    { label: "Alto Prado" },
    { label: "La Paragua" },
    { label: "San Francisco" },
    { label: "La Pica" },
    { label: "Periquera" },
    { label: "El Plomo" },
    { label: "Betel" }
];
const voices = [
    { label: 'Soprano' },
    { label: 'Contralto' },
    { label: 'Tenor' },
    { label: 'Barítono' },
    { label: 'Bajo' },
];

export {
    churchs,
    voices
}